services:
  synapse-init:
    image: busybox
    command: ['sh', '-c', 'chown -R 1000:1000 /data && chmod -R 777 /data']
    volumes:
      - synapse-data:/data
      - synapse-logs:/logs  # Add volume for logs
    networks:
      - synapse
    depends_on:
      - synapse-db

  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=1000
      - GID=1000
    volumes:
      - ./homeserver.yaml:/data/homeserver.yaml
      - synapse-data:/data
      - synapse-logs:/logs  # Mount the logs volume
    depends_on:
      - synapse-init
      - synapse-db
    networks:
      - synapse
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse.entrypoints=http"
      - "traefik.http.routers.synapse.rule=Host(`matrix.tat.systems`)"
      - "traefik.http.middlewares.synapse-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.synapse.middlewares=synapse-https-redirect"
      - "traefik.http.routers.synapse-secure.entrypoints=https"
      - "traefik.http.routers.synapse-secure.rule=Host(`matrix.tat.systems`)"
      - "traefik.http.routers.synapse-secure.tls=true"
      - "traefik.http.routers.synapse-secure.service=synapse"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
      - "traefik.docker.network=proxy"
        
  synapse-db:
    image: docker.io/postgres:15-alpine
    container_name: synapse-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=${SYNAPSE_POSTGRES_PASSWORD}
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse-db-data:/var/lib/postgresql/data
    networks:
      - synapse

  turn:
    image: coturn/coturn:latest
    container_name: turn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    environment:
      - TURN_SECRET=${SYNAPSE_TURN_SECRET}
      - LISTENING_PORT=3478
      - RELAY_IP=${TURN_PUBLIC_IP}
      - MIN_PORT=49152
      - MAX_PORT=65535
    command: >
      --lt-cred-mech
      --use-auth-secret
      --static-auth-secret=${SYNAPSE_TURN_SECRET}
      --realm=matrix.tat.systems
      --no-tls
      --no-dtls
    networks:
      - synapse
      - proxy

networks:
  synapse:
  proxy:
    external: true

volumes:
  synapse-data:
  synapse-db-data:
  synapse-logs:  # Define the logs volume